"""create recipes and recipe_cuisines tables

Revision ID: 6c10e3daa70d
Revises: 
Create Date: 2026-09-06 19:57:27.752507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c10e3daa70d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_cuisines',
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('cuisine', sa.Enum('ITALIAN', 'INDIAN', 'THAI', 'FRENCH', 'JAPANESE', 'CHINESE', 'MEXICAN', 'MIDDLE_EASTERN', 'GREEK', 'SPANISH', 'KOREAN', 'VIETNAMESE', 'BRITISH', 'AMERICAN', name='cuisine'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('recipe_id', 'cuisine')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_cuisines')
    op.drop_table('recipes')
    # ### end Alembic commands ###
